spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booklib?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    static-path-pattern: /resources/**
  